<?php

/*
 * Implementation of hook_materialized_view_info().
 */
function mv_forum_topic_materialized_view_info() {
  $mviews = array();
  $mviews[] = _mv_forum_topic();
  return $mviews;
}

function _mv_forum_topic() {
  $mview = new MaterializedView('mv_forum_topic');
  
  // Only include published nodes.
  $mview->addStaticFilter(new MVNodeColumn('status'), new MVEqualityOperator(1));

  // Prepare to filter by term IDs at runtime.
  $mview->addDynamicFilter(new MVNodeTerms(), new MVEqualityOperator());  

  // Sort by stickiness, then last node activity, and finally thread creation timestamp.
  $sortset = new MVSortSet('activity');
  $sortset->addSort(new MVNodeColumn('sticky'), MV_SORT_DESCENDING);
  $sortset->addSort(new MVLastNodeActivityTimestamp(), MV_SORT_DESCENDING);
  $sortset->addSort(new MVNodeColumn('created'), MV_SORT_DESCENDING);
  $mview->addSortSet($sortset);
  
  // Sort by stickiness and then thread creation timestamp.
  $sortset = new MVSortSet('creation');
  $sortset->addSort(new MVNodeColumn('sticky'), MV_SORT_DESCENDING);
  $sortset->addSort(new MVNodeColumn('created'), MV_SORT_DESCENDING);
  $mview->addSortSet($sortset);

  return $mview;
}
